//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace appProfiles.App_Folders.PortalPages {
    
    
    public partial class singup {
        
        /// <summary>
        /// signForm1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::appProfiles.App_Folders.PortalUserControl.signForm signForm1;
    }
}
